### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by flightcode** [nabeelio/phpvms#303]
When trying to install, I get:
```(1/1) UnexpectedValueException
The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied
in StreamHandler.php line 107
at StreamHandler->write(array('message' => 'The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', 'context' => array('exception' => object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'dev', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-05-06 06:36:04] dev.ERROR: The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied {"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \\"/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log\\" could not be opened: failed to open stream: Permission denied at /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107)[stacktrace]#0 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\\\Handler\\\\StreamHandler->write(Array)#1 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\\\Handler\\\\RotatingFileHandler->write(Array)#2 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\\\Logger->addRecord(400, \'The /var/www/va...\', Array)#4 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'The /var/www/va...\', Array)#5 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'The /var/www/va...\', Array)#6 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\\\Log\\\\Logger->error(\'The /var/www/va...\', Array)#7 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'The /var/www/va...\', Array)#8 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(Exception))#9 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(Exception))#10 /var/www/vap.openspotter.net/html/dashboard/index.php(18): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#11 {main}"} '))
in RotatingFileHandler.php line 107
at RotatingFileHandler->write(array('message' => 'The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', 'context' => array('exception' => object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'dev', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-05-06 06:36:04] dev.ERROR: The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied {"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \\"/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log\\" could not be opened: failed to open stream: Permission denied at /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107)[stacktrace]#0 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\\\Handler\\\\StreamHandler->write(Array)#1 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\\\Handler\\\\RotatingFileHandler->write(Array)#2 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\\\Logger->addRecord(400, \'The /var/www/va...\', Array)#4 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'The /var/www/va...\', Array)#5 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'The /var/www/va...\', Array)#6 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\\\Log\\\\Logger->error(\'The /var/www/va...\', Array)#7 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'The /var/www/va...\', Array)#8 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(Exception))#9 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(Exception))#10 /var/www/vap.openspotter.net/html/dashboard/index.php(18): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#11 {main}"} '))
in AbstractProcessingHandler.php line 37
at AbstractProcessingHandler->handle(array('message' => 'The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', 'context' => array('exception' => object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'dev', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-05-06 06:36:04] dev.ERROR: The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied {"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \\"/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log\\" could not be opened: failed to open stream: Permission denied at /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107)[stacktrace]#0 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\\\Handler\\\\StreamHandler->write(Array)#1 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\\\Handler\\\\RotatingFileHandler->write(Array)#2 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\\\Logger->addRecord(400, \'The /var/www/va...\', Array)#4 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'The /var/www/va...\', Array)#5 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'The /var/www/va...\', Array)#6 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\\\Log\\\\Logger->error(\'The /var/www/va...\', Array)#7 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'The /var/www/va...\', Array)#8 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(Exception))#9 /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(Exception))#10 /var/www/vap.openspotter.net/html/dashboard/index.php(18): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#11 {main}"} '))
in Logger.php line 337
at Logger->addRecord(400, 'The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', array('exception' => object(UnexpectedValueException)))
in Logger.php line 616
at Logger->error('The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', array('exception' => object(UnexpectedValueException)))
in Logger.php line 176
at Logger->writeLog('error', 'The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', array('exception' => object(UnexpectedValueException)))
in Logger.php line 87
at Logger->error('The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', array('exception' => object(UnexpectedValueException)))
in LogManager.php line 488
at LogManager->error('The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-06.log" could not be opened: failed to open stream: Permission denied', array('exception' => object(UnexpectedValueException)))
in Handler.php line 114
at Handler->report(object(UnexpectedValueException))
in HandleExceptions.php line 81
at HandleExceptions->handleException(object(UnexpectedValueException))```

**Comment by flightcode** [comment]
I also get this on the attempted ```composer install```:
```In ClassMapGenerator.php line 69:
Could not scan for classes inside "tests/TestCase.php" which does not appear to be a file nor a folder```

**Comment by nabeelio** [comment]
Make sure the permissions on the `/storage` folder are proper, so belonging to your user and set to `775`

**Comment by nabeelio** [comment]
That `composer install` error is the first time I'm seeing that, let me look into it.

**Comment by flightcode** [comment]
Thanks! In other situations, I get this error:
```In ClassMapGenerator.php line 69:
Could not scan for classes inside "tests/TestCase.php" which does not appear to be a file nor a folder```

**Comment by nabeelio** [comment]
Which situations? Are you running the `composer install` on the distribution package? Because that one already has all of the composer dependencies bundled in. It's still a bug, but just FYI, you shouldn't need to run the package installer there.

**Comment by nabeelio** [comment]
Can you try this with the latest dev build?

**Comment by flightcode** [comment]
I did it on the distribution package, though I'll try this on the dev build

**Comment by flightcode** [comment]
A different screen pops up, with 11 different errors. 
```UnexpectedValueException thrown with message "The stream or file "/var/www/vap.openspotter.net/html/dashboard/storage/logs/laravel-2019-05-09.log" could not be opened: failed to open stream: Permission denied"

Stacktrace:
#10 UnexpectedValueException in /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
#9 Monolog\Handler\StreamHandler:write in /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php:119
#8 Monolog\Handler\RotatingFileHandler:write in /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:39
#7 Monolog\Handler\AbstractProcessingHandler:handle in /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php:344
#6 Monolog\Logger:addRecord in /var/www/vap.openspotter.net/html/dashboard/vendor/monolog/monolog/src/Monolog/Logger.php:707
#5 Monolog\Logger:error in /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php:176
#4 Illuminate\Log\Logger:writeLog in /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/Logger.php:87
#3 Illuminate\Log\Logger:error in /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:498
#2 Illuminate\Log\LogManager:error in /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:114
#1 Illuminate\Foundation\Exceptions\Handler:report in /var/www/vap.openspotter.net/html/dashboard/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:81
#0 Illuminate\Foundation\Bootstrap\HandleExceptions:handleException in [internal]:0```

**Comment by flightcode** [comment]
I tried with a non-root user, and even with no composer errors, these errors still show up (chown and chmod for the whole phpvms, and the storage folder set). It's on a DigitalOcean Ubuntu 18.04 LTS.

**Comment by nabeelio** [comment]
Is there a way to get access into that VPS? You can message me on Discord.

**Comment by flightcode** [comment]
I can ssh into the vps itself of course, but no hardware (If that’s what
you mean)

**Comment by flightcode** [comment]
My discord is flightcode#5241 if you want

**Comment by flightcode** [comment]
Can confirm it is just an issue with user privileges. You need to make sure that `www-data` owns the folder, and that the `storage` and `bootstrap` are set to `775`.
