### ISSUE TITLE
submitting PIREP: Page Not Found

### ISSUE THREAD

**Issue by barf** [nabeelio/phpvms#676]
**Describe the bug**
Page not found error encountered when submitting PIREP

**Version**
phpVMS 7 beta 3

**To Reproduce**
1. Install phpVMS on Ubuntu with MariaDB
2. Configure a virtual airline, fleet, airports and hubs
3. Click PIREPS
4. Click File New PIREP

**Expected behavior**

**Error**
Page Not Found

Well, this is embarrassing, the page you requested does not exist.Click here to go back to the home page.
No query results for model [App\Models\Pirep] create

**Additional context**
```[previous exception] [object] (ErrorException(code: 0): Undefined variable: subfleets at /var/www/phpvms-beta/storage/framework/views/0c6975c8c5b97c4c961f7aaa571a640c3a9b5fa0.php:31)
[stacktrace]
#0 /var/www/phpvms-beta/storage/framework/views/0c6975c8c5b97c4c961f7aaa571a640c3a9b5fa0.php(31): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/phpvms...')
#2 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#3 /var/www/phpvms-beta/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get()
#4 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#5 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#6 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /var/www/phpvms-beta/storage/framework/views/b00bdd59425f42c93b9bab3916064322068a0ad3.php(12): Illuminate\\View\\View->render()
#8 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/phpvms...')
#9 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#10 /var/www/phpvms-beta/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get()
#11 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#12 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#13 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#14 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#15 /var/www/phpvms-beta/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent()
#16 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct()
#17 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router::toResponse()
#18 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Router->prepareResponse()
#19 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/phpvms-beta/app/Http/Middleware/SetActiveTheme.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\SetActiveTheme->handle()
#22 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#24 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#26 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#28 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/phpvms-beta/app/Http/Middleware/InstalledCheck.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\InstalledCheck->handle()
#36 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#38 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#40 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#42 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#49 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/phpvms-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/phpvms-beta/public/index.php(22): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"}

**Comment by nabeelio** [comment]
This was fixed in the latest dev versions
